apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-component-name
    app.kubernetes.io/part-of: my-application
  name: component-example
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: component-example
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: component-example
    spec:
      containers:
      - image: docker.io/openshift/hello-openshift
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
